Fixed minor errors on initializations scripts

diff --git a/bin/tenants b/bin/tenants
--- a/bin/tenants
+++ b/bin/tenants
@@ -2,15 +2,33 @@
 
 readonly env=${SYMFONY_ENV:-prod}
 
-if [[ ! -d app/config ]]; then
-  echo "Error, the script must be executed from root app dir"
-  exit 1
-fi
+if [[ -n ${CONSUL_PREFIX} ]]; then
+  [[ -n ${DEBUG} ]] && echo "==> Loading tenants info from Consul ${CONSUL_HTTP_ADDR}" >> /dev/stderr
 
-readonly tenants=$(ls -1d app/config/*/ | egrep -v '(bundles|common)' | cut -d'/' -f 3)
+  wait-for-it ${CONSUL_HTTP_ADDR:-'consul:8500'} --timeout=0 --strict
 
-for tenant in $tenants; do
-  if [[ -f app/config/tenants/${tenant}/config_${env}.yml ]]; then
-     echo $tenant
+  tenants=$(consul kv get -keys ${consul_prefix}/ | sed "s#${consul_prefix}/##" | sed 's#/$##')
+  for tenant in $tenants; do
+    echo $tenant
+  done
+  
+else
+
+  tenants_folder=${TENANTS_CONFIG_PATH:-app/config/tenants}
+
+  [[ -n ${DEBUG} ]] && echo "==> Loading tenants info from filesystem @ ${tenants_folder}" >> /dev/stderr
+
+  if [[ ! -d ${tenants_folder} ]]; then
+    echo "Error, the script must be executed from root app dir"
+    exit 1
   fi
-done
+
+  readonly tenants=$(ls -1d ${tenants_folder}/*/ | cut -d'/' -f 4)
+
+  for tenant in $tenants; do
+    if [[ -f ${tenants_folder}/${tenant}/config_${env}.yml ]]; then
+      echo $tenant
+    fi
+  done
+
+fi
